{
  "baseline": "-54.855",
  "intrinsic_left.x.x": "0.678378",
  "intrinsic_left.x.y": "1.20354",
  "intrinsic_left.x.z": "0.501059",
  "intrinsic_left.y.x": "0.494392",
  "intrinsic_left.y.y": "0.155175",
  "intrinsic_left.y.z": "-0.394761",
  "intrinsic_left.z.x": "-0.000654849",
  "intrinsic_left.z.y": "0.000530154",
  "intrinsic_left.z.z": "0.271441",
  "intrinsic_right.x.x": "0.678195",
  "intrinsic_right.x.y": "1.20321",
  "intrinsic_right.x.z": "0.500098",
  "intrinsic_right.y.x": "0.498541",
  "intrinsic_right.y.y": "0.148552",
  "intrinsic_right.y.z": "-0.376618",
  "intrinsic_right.z.x": "-7.96745e-05",
  "intrinsic_right.z.y": "0.000170151",
  "intrinsic_right.z.z": "0.255897",
  "rectified.0.fx": "1329.46",
  "rectified.0.fy": "1329.46",
  "rectified.0.height": "1080",
  "rectified.0.ppx": "966.865",
  "rectified.0.ppy": "535.722",
  "rectified.0.width": "1920",
  "rectified.1.fx": "886.305",
  "rectified.1.fy": "886.305",
  "rectified.1.height": "720",
  "rectified.1.ppx": "644.577",
  "rectified.1.ppy": "357.148",
  "rectified.1.width": "1280",
  "rectified.10.fx": "886.305",
  "rectified.10.fy": "886.305",
  "rectified.10.height": "0",
  "rectified.10.ppx": "364.577",
  "rectified.10.ppy": "357.148",
  "rectified.10.width": "0",
  "rectified.11.fx": "709.044",
  "rectified.11.fy": "709.044",
  "rectified.11.height": "0",
  "rectified.11.ppx": "291.661",
  "rectified.11.ppy": "285.718",
  "rectified.11.width": "0",
  "rectified.12.fx": "0",
  "rectified.12.fy": "0",
  "rectified.12.height": "400",
  "rectified.12.ppx": "0",
  "rectified.12.ppy": "0",
  "rectified.12.width": "640",
  "rectified.13.fx": "0",
  "rectified.13.fy": "0",
  "rectified.13.height": "576",
  "rectified.13.ppx": "0",
  "rectified.13.ppy": "0",
  "rectified.13.width": "576",
  "rectified.14.fx": "0",
  "rectified.14.fy": "0",
  "rectified.14.height": "720",
  "rectified.14.ppx": "0",
  "rectified.14.ppy": "0",
  "rectified.14.width": "720",
  "rectified.15.fx": "0",
  "rectified.15.fy": "0",
  "rectified.15.height": "1152",
  "rectified.15.ppx": "0",
  "rectified.15.ppy": "0",
  "rectified.15.width": "1152",
  "rectified.2.fx": "590.87",
  "rectified.2.fy": "590.87",
  "rectified.2.height": "480",
  "rectified.2.ppx": "323.051",
  "rectified.2.ppy": "238.098",
  "rectified.2.width": "640",
  "rectified.3.fx": "590.87",
  "rectified.3.fy": "590.87",
  "rectified.3.height": "480",
  "rectified.3.ppx": "427.051",
  "rectified.3.ppy": "238.098",
  "rectified.3.width": "848",
  "rectified.4.fx": "443.153",
  "rectified.4.fy": "443.153",
  "rectified.4.height": "360",
  "rectified.4.ppx": "322.288",
  "rectified.4.ppy": "178.574",
  "rectified.4.width": "640",
  "rectified.5.fx": "295.435",
  "rectified.5.fy": "295.435",
  "rectified.5.height": "240",
  "rectified.5.ppx": "213.526",
  "rectified.5.ppy": "119.049",
  "rectified.5.width": "424",
  "rectified.6.fx": "295.435",
  "rectified.6.fy": "295.435",
  "rectified.6.height": "240",
  "rectified.6.ppx": "161.526",
  "rectified.6.ppy": "119.049",
  "rectified.6.width": "320",
  "rectified.7.fx": "332.365",
  "rectified.7.fy": "332.365",
  "rectified.7.height": "270",
  "rectified.7.ppx": "241.716",
  "rectified.7.ppy": "133.93",
  "rectified.7.width": "480",
  "rectified.8.fx": "984.784",
  "rectified.8.fy": "984.784",
  "rectified.8.height": "800",
  "rectified.8.ppx": "645.085",
  "rectified.8.ppy": "396.831",
  "rectified.8.width": "1280",
  "rectified.9.fx": "664.729",
  "rectified.9.fy": "664.729",
  "rectified.9.height": "540",
  "rectified.9.ppx": "483.433",
  "rectified.9.ppy": "267.861",
  "rectified.9.width": "960",
  "world2left_rot.x.x": "0.999987",
  "world2left_rot.x.y": "-0.000649463",
  "world2left_rot.x.z": "0.00514332",
  "world2left_rot.y.x": "0.000646526",
  "world2left_rot.y.y": "1",
  "world2left_rot.y.z": "0.000572634",
  "world2left_rot.z.x": "-0.00514369",
  "world2left_rot.z.y": "-0.000569301",
  "world2left_rot.z.z": "0.999987",
  "world2right_rot.x.x": "1",
  "world2right_rot.x.y": "0.000827957",
  "world2right_rot.x.z": "-0.000156607",
  "world2right_rot.y.x": "-0.000828046",
  "world2right_rot.y.y": "1",
  "world2right_rot.y.z": "-0.000570905",
  "world2right_rot.z.x": "0.000156134",
  "world2right_rot.z.y": "0.000571034",
  "world2right_rot.z.z": "1"
}